
cub (200, 208)
/cis/home/achatto1/.local/lib/python3.8/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='none' instead.
  warnings.warn(warning.format(ret))
  0%|                                                                                                                                                                             | 0/38 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_concept_qa.py", line 267, in <module>
    main(dataset_name)
  File "train_concept_qa.py", line 217, in main
    train(train_ds, dataset_name, model, optimizer, scheduler, gpt_answers)
  File "train_concept_qa.py", line 81, in train
    for batch_i, data in tqdm.tqdm(enumerate(dataloader), total=len(dataloader)):
  File "/cis/home/achatto1/.local/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/cis/home/achatto1/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/cis/home/achatto1/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/cis/home/achatto1/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/cis/home/achatto1/.local/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/cis/home/achatto1/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/cis/home/achatto1/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/cis/home/achatto1/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/cis/home/achatto1/conceptqa_vip/CUB_dataset.py", line 68, in __getitem__
    img = Image.open(img_path).convert("RGB")
  File "/cis/home/achatto1/anaconda3/lib/python3.8/site-packages/PIL/Image.py", line 3243, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/CUB/CUB_200_2011//images/189.Red_bellied_Woodpecker/Red_Bellied_Woodpecker_0103_180803.jpg'